"""
Approved explanations — final explanations that municipalities see in their portal.
"""

from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, func
from sqlalchemy.orm import relationship
from datetime import datetime
from enum import Enum

from backend.database import Base


class ApprovedExplanationSource(str, Enum):
    """Where the approved explanation came from."""
    AUTO = "auto"  # Generated automatically from smart explanation engine
    PRESET = "preset"  # CPA selected a preset
    CUSTOM = "custom"  # CPA or employee wrote custom text
    SUGGESTION = "suggestion"  # Approved from an employee suggestion


class ApprovedExplanation(Base):
    """
    Represents a final approved explanation that is shown to municipalities.
    
    This is what municipalities see in their budget portal. It can be:
    1. Auto-generated by SmartExplanationEngine (fallback)
    2. Created from a preset explanation (CPA chose one)
    3. Custom written by CPA or approved from employee suggestion
    
    Attributes:
        id: Primary key
        budget_line_id: Which budget line this explanation is for
        municipality_id: Which municipality's budget
        month: Month in YYYY-MM format
        topic_code: Budget code
        final_text: The explanation text shown to municipality
        approved_by: ID of CPA admin who approved this
        source: Where it came from (auto, preset, custom, suggestion)
        suggestion_id: If source=suggestion, link back to the suggestion
        created_at: When approved
        updated_at: Last modification time
    """
    __tablename__ = "approved_explanations"
    
    id = Column(Integer, primary_key=True, index=True)
    
    # What is this for?
    budget_line_id = Column(Integer, ForeignKey("budget_lines.id"), nullable=False, index=True)
    municipality_id = Column(Integer, ForeignKey("municipalities.id"), nullable=False, index=True)
    month = Column(String(7), nullable=False, index=True)  # YYYY-MM format
    topic_code = Column(String(10), nullable=False, index=True)
    
    # The explanation content
    final_text = Column(String(1000), nullable=False)
    
    # Approval info
    approved_by = Column(Integer, ForeignKey("users.id"), nullable=False)
    source = Column(String(20), nullable=False)  # auto, preset, custom, suggestion
    suggestion_id = Column(Integer, ForeignKey("explanation_suggestions.id"), nullable=True)
    
    # Timestamps
    created_at = Column(DateTime, default=func.now(), nullable=False, index=True)
    updated_at = Column(DateTime, default=func.now(), onupdate=func.now(), nullable=False)
    
    # Relationships
    budget_line = relationship("BudgetLine", foreign_keys=[budget_line_id], backref="approved_explanations")
    municipality = relationship("Municipality", foreign_keys=[municipality_id], backref="approved_explanations")
    approver = relationship("User", foreign_keys=[approved_by], backref="explanations_approved")
    suggestion = relationship("ExplanationSuggestion", foreign_keys=[suggestion_id])
